dip/config/routes.rb
Rails.application.routes.draw do
	resources :parse_tasks do
		member do
			put 'parse'
			post 'export'
		end
	end

	resources :litres_books, only: [:index, :show] do
		collection do
			post 'search'
			post 'export'
		end
		member do
			post 'page'
		end
	end

	resources :leonardo_products, only: [:index, :show] do
		collection do
			post 'search'
			post 'export'
		end
		member do
			post 'page'
		end
	end

	get 'home', to: "home#index"

	root "home#index"
end

dip/app/models/litres_book.rb
class LitresBook < ApplicationRecord
#after_create_commit { broadcast_append_to('log', partial: 'parse_tasks/log', locals: { header: "Litres.ru", info: "Book added to db: #{self.name}", url: "Db" }, target: "log") }


	def self.to_csv
		attributes = %w{name author series}

		CSV.generate(headers: true) do |csv|
			csv << attributes

			all.each do |litres_book|
				csv << litres_book.attributes.values_at(*attributes)
			end
		end
	end
end

dip/app/controllers/litres_books_controller.rb
class LitresBooksController < ApplicationController
	before_action :set_litres_book, only: %i[ show ]
	before_action :set_litres_books_from_params, only: %i[ search ]
	before_action :set_litres_books_from_session, only: %i[ index page export ]

	def index
		@page = session[:litres_current_page]
		if not @page.nil?
			@litres_books = @litres_books.limit(10).offset(10 * (@page - 1))
		end
		respond_to do |format|
			format.html
		end
	end

	def show
	end

	def search
		respond_to do |format|
			format.turbo_stream do
				render turbo_stream: [
					turbo_stream.update("litres_books", partial: "litres_books/list", locals: { litres_books: @litres_books, page_num: 1 }, target: "litres_books") ]
			end
		end
	end

	def page
		page = params[:id].to_i
		session[:litres_current_page] = page
		@litres_books = @litres_books.limit(10).offset(10 * (page - 1))
		respond_to do |format|
			if page != 0 and @litres_books.length != 0
				format.turbo_stream { render turbo_stream: turbo_stream.update("litres_books", partial: "litres_books/list", locals: { litres_books: @litres_books, page_num: page }, target: "litres_books") }
			else 
				format.turbo_stream
			end
		end
	end

	def export
		respond_to do |format|
			if not @atr.nil?
				format.csv { send_data @litres_books.to_csv, filename: "litres-books.csv" }
			else
				format.html { redirect_to litres_books_url, alert: "Export failed: do a search first" }
			end
		end
	end

	private

	def set_litres_book
		@litres_book = LitresBook.find(params[:id])
	end

	def sort_tags_genres(litres_books, searched_str)
		for request in searched_str.split(',')
			request = request.strip
			litres_books = litres_books.where("ARRAY_TO_STRING(genres, ',') ILIKE ? OR ARRAY_TO_STRING(tags, ',') ILIKE ?", "%#{request}%", "%#{request}%")
		end

		return litres_books
	end

	def set_litres_books_from_session
		@atr = session[:litres_searched_books]
		if not @atr.nil?
			@litres_books = LitresBook.where("name ILIKE ? AND author ILIKE ? AND series ILIKE ? AND grade_litres >= ? AND grade_litres <= ? AND evaluators_litres >= ? AND evaluators_litres <= ? AND price >= ? AND price <= ?", "%#{@atr["name"]}%", "%#{@atr["author"]}%", "%#{@atr["series"]}%", @atr["min_litres_grade"], @atr["max_litres_grade"], @atr["min_litres_count_of_evaluators"], @atr["max_litres_count_of_evaluators"], @atr["min_price"], @atr["max_price"])
			@litres_books = sort_tags_genres(@litres_books, @atr["tags_genres"])
			@litres_books = @litres_books.order(@atr["order"])
		end
	end

	def set_litres_books_from_params
		@litres_books = LitresBook.where("name ILIKE ? AND author ILIKE ? AND series ILIKE ? AND grade_litres >= ? AND grade_litres <= ? AND evaluators_litres >= ? AND evaluators_litres <= ? AND price >= ? AND price <= ?", "%#{params[:name]}%", "%#{params[:author]}%", "%#{params[:series]}%", params[:min_litres_grade], params[:max_litres_grade], params[:min_litres_count_of_evaluators], params[:max_litres_count_of_evaluators], params[:min_price], params[:max_price]).limit(10)
		@litres_books = sort_tags_genres(@litres_books, params[:tags_genres])
		@litres_books = @litres_books.order(params[:order])
		session[:litres_searched_books] = params
	end

end

dip/app/helpers/litres_books_helper.rb
module LitresBooksHelper
end

dip/app/views/litres_books/_form.html.erb
<%= form_with url: search_litres_books_url, class: "row g-3", method: :post do |form| %>
	<div class="col-md-12">
		<%= form.label :name, class: "form-label", for: "inputName" %>
		<%= form.text_field :name, class: "form-control", id: "inputName" %>
	</div>

	<div class="col-md-12 border-bottom pb-3">
		<%= form.radio_button :order, "name", class: "form-check-input", checked: true %>
		<%= form.label :order, "Order by name", class: "form-check-label" %>
	</div>

	<div class="col-md-12">
		<%= form.label :author, class: "form-label", for: "inputAuthor" %>
		<%= form.text_field :author, class: "form-control", id: "inputAuthor" %>
	</div>

	<div class="col-md-12 border-bottom pb-3">
		<%= form.radio_button :order, "author", class: "form-check-input" %>
		<%= form.label :order, "Order by author", class: "form-check-label" %>
	</div>

	<div class="col-md-12"> 
		<%= form.label :series, class: "form-label", for: "inputSeries" %>
		<%= form.text_field :series, class: "form-control", id: "inputSeries" %>
	</div>

	<div class="col-md-12 border-bottom pb-3">
		<%= form.radio_button :order, "series", class: "form-check-input" %>
		<%= form.label :order, "Order by series", class: "form-check-label" %>
	</div>

	<div class="col-md-6"> 
		<%= form.label :min_litres_grade, class: "form-label", for: "inputMinGrade" %>
		<%= form.number_field :min_litres_grade, in: 0.0..5.0, step: 0.1, value: 0.0, id: "inputMinGrade", class: "form-control" %>
	</div>

	<div class="col-md-6"> 
		<%= form.label :max_litres_grade, class: "form-label", for: "inputMaxGrade" %>
		<%= form.number_field :max_litres_grade, in: 0.0..5.0, step: 0.1, value: 5.0, id: "inputMaxGrade", class: "form-control" %>
	</div>

	<div class="col-md-12 border-bottom pb-3">
		<%= form.radio_button :order, "grade_litres", class: "form-check-input" %>
		<%= form.label :order, "Order by grade", class: "form-check-label" %>
	</div>

	<div class="col-md-6"> 
		<%= form.label :min_litres_count_of_evaluators, class: "form-label", for: "inputMinEval" %>
		<%= form.number_field :min_litres_count_of_evaluators, in: 0..1000000, step: 1, value: 0, id: "inputMinEval", class: "form-control" %>
	</div>

	<div class="col-md-6"> 
		<%= form.label :max_litres_count_of_evaluators, class: "form-label", for: "inputMaxEval" %>
		<%= form.number_field :max_litres_count_of_evaluators, in: 0..1000000, step: 1, value: 1000000, id: "inputMaxEval", class: "form-control" %>
	</div>

	<div class="col-md-12 border-bottom pb-3">
		<%= form.radio_button :order, "evaluators_litres", class: "form-check-input" %>
		<%= form.label :order, "Order by evaluators", class: "form-check-label" %>
	</div>

	<div class="col-md-6"> 
		<%= form.label :min_price, class: "form-label", for: "inputMinPrice" %>
		<%= form.number_field :min_price, in: 0..1000000, step: 1, value: 0, id: "inputMinPrice", class: "form-control" %>
	</div>

	<div class="col-md-6"> 
		<%= form.label :max_price, class: "form-label", for: "inputMaxPrice" %>
		<%= form.number_field :max_price, in: 0..1000000, step: 1, value: 1000000, id: "inputMaxPrice", class: "form-control" %>
	</div>

	<div class="col-md-12 border-bottom pb-3">
		<%= form.radio_button :order, "price", class: "form-check-input" %>
		<%= form.label :order, "Order by price", class: "form-check-label" %>
	</div>

	<div class="col-md-12"> 
		<%= form.label :tags_genres, class: "form-label", for: "inputTagsGenres" %>
		<%= form.text_area :tags_genres, id: "inputTagsGenres", class: "form-control" %>
		<div id="tagsGenresHelp" class="form-text">List tags and genres separated by commas</div>
	</div>

	<div class="col-md-12">
		<%= form.submit "Search", class: "btn btn-primary" %>
	</div>
<% end %>

dip/app/views/litres_books/_list.html.erb
<div class="row g-3">
	<div class="col-md-12">
		<table class="table table-striped table-hover">
			<thead>
				<tr>
					<th scope="col">Name</th>
					<th scope="col">Author</th>
					<th scope="col">Price</th>
				</tr>
			</thead>
			<tbody>
				<% litres_books.each do |litres_book| %>
					<tr>
						<%= render partial: "litres_book_demo", locals: { litres_book: litres_book } %>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>

	<div class="col-md-4">
		<%= button_to "Previous page", page_litres_book_url(page_num-1), method: "post", class: "btn btn-primary" %>
	</div>
	<div class="col-md-4">
		<div class="text-center">
			Page <%= page_num %>
		</div>
	</div>
	<div class="col-md-4">
		<div class="float-end">
		<%= button_to "Next page", page_litres_book_url(page_num+1), method: "post", class: "btn btn-primary" %>
		</div>
	</div>
</div>

dip/app/views/litres_books/_litres_book.html.erb
<div class="container">
	<div class="row ">
		<div class="col">
			<img width="300" height="500" src="<%= @litres_book.img %>" class="rounded" >
			<p>
				<strong>Description:</strong>
				<%= @litres_book.description %>
			</p>
		</div>
		<div class="col">
			<p>
				<strong>Name:</strong>
				<%= @litres_book.name %>
			</p>
			<p>
				<strong>Author:</strong>
				<%= @litres_book.author %>
			</p>
			<p>
				<strong>Main genre:</strong>
				<%= @litres_book.main_genre %>
			</p>
			<p>
				<strong>Series:</strong>
				<%= @litres_book.series %>
			</p>
			<p>
				<strong>Grade(litres):</strong>
				<%= @litres_book.grade_litres %>
			</p>
			<p>
				<strong>Grade(livelib):</strong>
				<%= @litres_book.grade_livelib %>
			</p>
			<p>
				<strong>Count of evaluators(litres):</strong>
				<%= @litres_book.evaluators_litres %>
			</p>
			<p>
				<strong>Count of evaluators(livelib):</strong>
				<%= @litres_book.evaluators_livelib %>
			</p>
			<p>
				<strong>Genres:</strong>
				<%= @litres_book.genres %>
			</p>
			<p>
				<strong>Tags:</strong>
				<%= @litres_book.tags %>
			</p>
			<p>
				<strong>Age limit:</strong>
				<%= @litres_book.age_limit %>
			</p>
			<p>
				<strong>Release date on web-site:</strong>
				<%= @litres_book.release_on_website %>
			</p>
			<p>
				<strong>Release date in world:</strong>
				<%= @litres_book.release_on_world %>
			</p>
			<p>
				<strong>Translate release date:</strong>
				<%= @litres_book.release_translate %>
			</p>
			<p>
				<strong>Amount of page:</strong>
				<%= @litres_book.book_size %>
			</p>
			<p>
				<strong>ISBN:</strong>
				<%= @litres_book.isbn %>
			</p>
			<p>
				<strong>Price:</strong>
				<%= @litres_book.price %>
			</p>
		</div>
	</div>
</div>
<%= link_to "To source page", @litres_book.page_url %>

dip/app/views/litres_books/_litres_book_demo.html.erb
<td>
	<a href="<%= litres_book_url(litres_book) %>">
		<%= litres_book.name %>
	</a>
</td>
<td>
	<%= litres_book.author %>
</td>
<td>
	<%= litres_book.price %>
</td>

dip/app/views/litres_books/_navbar.html.erb
<ul class="nav nav-tabs justify-content-center">
	<li class="nav-item">
		<a class="nav-link" href="/parse_tasks">Tasks</a>
	</li>
	<li class="nav-item">
		<a class="nav-link active" aria-current="page" href="/litres_books">Litres</a>
	</li>
	<li class="nav-item">
		<a class="nav-link" href="/leonardo_products">Leonardo</a>
	</li>
</ul>

dip/app/views/litres_books/index.html.erb
<%= turbo_stream_from "litres_books" %>
<%= turbo_stream_from "litres_books_page" %>
<%= turbo_stream_from "litres_search_form" %>

<div id="navbar">
	<%= render partial: "layouts/navbar", locals: { active: 3 }%>
</div>

<div id="tabs">
	<%= render partial: "layouts/tabs", locals: { active: 1 }%>
</div>

<div class="container mt-4">
	<% if not notice.nil?%>
		<div class="alert alert-success" role="alert">
			<%= notice %>
		</div>
	<% end %>

	<% if not alert.nil?%>
		<div class="alert alert-danger" role="alert">
			<%= alert %>
		</div>
	<% end %>

	<div class="row"> <div class="col-4">
			<h1>Litres books</h1>

			<div class="vstack gap-3">
				<div id="litres_search_form">
					<%= render partial: "form" %>
				</div>

				<div>
					<%= button_to "Export", "/litres_books/export.csv", method: "post", class: "btn btn-primary" %>
				</div>
			</div>
		</div>
		<div class="col-8 border-start">
			<div id="litres_books">
				<% if not @litres_books.nil? and @page != 0 and not @page.nil?%>
					<%= render partial: "litres_books/list", locals: { litres_books: @litres_books, page_num: @page } %>
				<% end %>
			</div>
		</div>
	</div>
</div>

dip/app/views/litres_books/show.html.erb
<div id="navbar">
	<%= render partial: "layouts/navbar", locals: { active: 3 }%>
</div>

<div id="tabs">
	<%= render partial: "layouts/tabs", locals: { active: 1 }%>
</div>

<div class="container mt-4">
	<%= render @litres_book %>
	<div>
		<%= link_to "Back to litres_books", litres_books_path %>
	</div>
</div>