dip/config/routes.rb
Rails.application.routes.draw do
	resources :parse_tasks do
		member do
			put 'parse'
			post 'export'
		end
	end

	resources :litres_books, only: [:index, :show] do
		collection do
			post 'search'
			post 'export'
		end
		member do
			post 'page'
		end
	end

	resources :leonardo_products, only: [:index, :show] do
		collection do
			post 'search'
			post 'export'
		end
		member do
			post 'page'
		end
	end

	get 'home', to: "home#index"

	root "home#index"
end

dip/app/models/leonardo_product.rb
class LeonardoProduct < ApplicationRecord
#after_create_commit { broadcast_append_to('log', partial: 'parse_tasks/log', locals: { header: "Leonardo.by", info: "Product added to db: #{self.name}", url: "Db" }, target: "log") }

	def self.to_csv
		attributes = %w{name brend price}

		CSV.generate(headers: true) do |csv|
			csv << attributes

			all.each do |litres_book|
				csv << litres_book.attributes.values_at(*attributes)
			end
		end
	end
end

dip/app/controllers/leonardo_products_controller.rb
class LeonardoProductsController < ApplicationController
	before_action :set_leonardo_products, only: %i[ show ]
	before_action :set_leonardo_products_from_params, only: %i[ search ]
	before_action :set_leonardo_products_from_session, only: %i[ index page export ]

	def index
		@page = session[:leonardo_current_page]
		if not @page.nil?
			@leonardo_products = @leonardo_products.limit(10).offset(10 * (@page - 1))
		end
		respond_to do |format|
			format.html
		end
	end

	def show
	end

	def search
		session[:leonardo_current_page] = 1
		respond_to do |format|
			format.turbo_stream do
				render turbo_stream: [
					turbo_stream.update("leonardo_products", partial: "leonardo_products/list", locals: { leonardo_products: @leonardo_products, page_num: 1 }, target: "leonardo_products") ]
			end
		end
	end

	def page
		page = params[:id].to_i
		session[:leonardo_current_page] = page
		@leonardo_products = @leonardo_products.limit(10).offset(10 * (page - 1))
		respond_to do |format|
			if page != 0 and @leonardo_products.length != 0
				format.turbo_stream { render turbo_stream: turbo_stream.update("leonardo_products", partial: "leonardo_products/list", locals: { leonardo_products: @leonardo_products, page_num: page }, target: "leonardo_products") }
			else 
				format.turbo_stream
			end
		end
	end

	def export
		respond_to do |format|
			if not atr.nil?
				format.csv { send_data @leonardo_products.to_csv, filename: "leonardo-products.csv" }
			else
				format.html { redirect_to leonardo_products_url, alert: "Export failed: do a search first" }
			end
		end
	end 
	private

	def set_leonardo_products
		@leonardo_product = LeonardoProduct.find(params[:id])
	end

	def set_leonardo_products_from_session
		atr = session[:leonardo_searched_products]
		if not atr.nil?
			@leonardo_products = LeonardoProduct.where("name ILIKE ? AND brend ILIKE ? AND rating >= ? AND rating <= ? AND evaluators >= ? AND evaluators <= ? AND price >= ? AND price <= ? AND instock = ?", "%#{atr["name"]}%", "%#{atr["brend"]}%", atr["min_rating"], atr["max_rating"], atr["min_count_of_evaluators"], atr["max_count_of_evaluators"], atr["min_price"], atr["max_price"], get_instock(atr["in_stock"]))
			@leonardo_products = @leonardo_products.order(atr["order"])
		end
	end

	def set_leonardo_products_from_params
		@leonardo_products = LeonardoProduct.where("name ILIKE ? AND brend ILIKE ? AND rating >= ? AND rating <= ? AND evaluators >= ? AND evaluators <= ? AND price >= ? AND price <= ? AND instock = ?", "%#{params[:name]}%", "%#{params[:brend]}%", params[:min_rating], params[:max_rating], params[:min_count_of_evaluators], params[:max_count_of_evaluators], params[:min_price], params[:max_price], get_instock(params[:in_stock])).limit(10)
		@leonardo_products = @leonardo_products.order(params[:order])
		session[:leonardo_searched_products] = params
	end

	def get_instock(stock)
		return stock.nil?
	end
end

dip/app/views/leonardo_products/_form.html.erb
<%= form_with url: search_leonardo_products_url, class: "row g-3", method: :post do |form| %>
	<div class="col-md-12">
		<%= form.label :name, class: "form-label", for: "inputName" %>
		<%= form.text_field :name, class: "form-control", id: "inputName" %>
	</div>

	<div class="col-md-12 border-bottom pb-3">
		<%= form.radio_button :order, "name", class: "form-check-input", checked: true %>
		<%= form.label :order, "Order by name", class: "form-check-label" %>
	</div>

	<div class="col-md-12">
		<%= form.label :brend, class: "form-label", for: "inputBrend" %>
		<%= form.text_field :brend, class: "form-control", id: "inputBrend" %>
	</div>

	<div class="col-md-12 border-bottom pb-3">
		<%= form.radio_button :order, "brend", class: "form-check-input" %>
		<%= form.label :order, "Order by brend", class: "form-check-label" %>
	</div>

	<div class="col-md-6"> 
		<%= form.label :min_rating, class: "form-label", for: "inputMinRating" %>
		<%= form.number_field :min_rating, in: 0.0..5.0, step: 0.1, value: 0.0, id: "inputMinRating", class: "form-control" %>
	</div>

	<div class="col-md-6"> 
		<%= form.label :max_rating, class: "form-label", for: "inputMaxRating" %>
		<%= form.number_field :max_rating, in: 0.0..5.0, step: 0.1, value: 5.0, id: "inputMaxRating", class: "form-control" %>
	</div>

	<div class="col-md-12 border-bottom pb-3">
		<%= form.radio_button :order, "rating", class: "form-check-input" %>
		<%= form.label :order, "Order by rating", class: "form-check-label" %>
	</div>

	<div class="col-md-6"> 
		<%= form.label :min_count_of_evaluators, class: "form-label", for: "inputMinEval" %>
		<%= form.number_field :min_count_of_evaluators, in: 0..1000000, step: 1, value: 0, id: "inputMinEval", class: "form-control" %>
	</div>

	<div class="col-md-6"> 
		<%= form.label :max_count_of_evaluators, class: "form-label", for: "inputMaxEval" %>
		<%= form.number_field :max_count_of_evaluators, in: 0..1000000, step: 1, value: 1000000, id: "inputMaxEval", class: "form-control" %>
	</div>

	<div class="col-md-12 border-bottom pb-3">
		<%= form.radio_button :order, "evaluators", class: "form-check-input" %>
		<%= form.label :order, "Order by evaluators", class: "form-check-label" %>
	</div>

	<div class="col-md-6"> 
		<%= form.label :min_price, class: "form-label", for: "inputMinPrice" %>
		<%= form.number_field :min_price, in: 0..1000000, step: 1, value: 0, id: "inputMinPrice", class: "form-control" %>
	</div>

	<div class="col-md-6"> 
		<%= form.label :max_price, class: "form-label", for: "inputMaxPrice" %>
		<%= form.number_field :max_price, in: 0..1000000, step: 1, value: 1000000, id: "inputMaxPrice", class: "form-control" %>
	</div>

	<div class="col-md-12 border-bottom pb-3">
		<%= form.radio_button :order, "price", class: "form-check-input" %>
		<%= form.label :order, "Order by price", class: "form-check-label" %>
	</div>

	<div class="col-md-12">
		<%= form.label :in_stock, class: "form-ckeck-label", for: "inputInStock" %>
		<%= form.check_box :instock, class: "form-check-input", id: "inputInStock", checked: true %>
	</div>

	<div class="col-md-12">
		<%= form.submit "Search", class: "btn btn-primary" %>
	</div>
<% end %>

dip/app/views/leonardo_products/_leonardo_product.html.erb
<div class="container">
	<div class="row ">
		<div class="col">
			<img width="300" height="500" src="<%= @leonardo_product.img %>" class="rounded" >
			<p>
				<strong>Description:</strong>
				<%= @leonardo_product.desc %>
			</p>
		</div>
		<div class="col">
			<p>
				<strong>Category name:</strong>
				<%= @leonardo_product.category_name %>
			</p>
			<p>
				<strong>Name:</strong>
				<%= @leonardo_product.name %>
			</p>
			<p>
				<strong>Brend:</strong>
				<%= @leonardo_product.brend %>
			</p>
			<p>
				<strong>Rating:</strong>
				<%= @leonardo_product.rating %>
			</p>
			<p>
				<strong>Count of evaluators:</strong>
				<%= @leonardo_product.evaluators %>
			</p>
			<p>
				<strong>In stock:</strong>
				<%= @leonardo_product.instock %>
			</p>
			<p>
				<strong>Price:</strong>
				<%= @leonardo_product.price %>
			</p>
		</div>
	</div>
</div>
<%= link_to "To source page", @leonardo_product.source_url %>

dip/app/views/leonardo_products/_leonardo_product_demo.html.erb
<td>
	<a href="<%= leonardo_product_url(leonardo_product) %>">
		<%= leonardo_product.name %>
	</a>
</td>
<td>
	<%= leonardo_product.brend %>
</td>
<td>
	<%= leonardo_product.price %>
</td>

dip/app/views/leonardo_products/_list.html.erb
<div class="row g-3">
	<div class="col-md-12">
		<table class="table table-striped table-hover">
			<thead>
				<tr>
					<th scope="col">Name</th>
					<th scope="col">Brend</th>
					<th scope="col">Price</th>
				</tr>
			</thead>
			<tbody>
				<% leonardo_products.each do |leonardo_product| %>
					<tr>
						<%= render partial: "leonardo_product_demo", locals: { leonardo_product: leonardo_product } %>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>

	<div class="col-md-4">
		<%= button_to "Previous page", page_leonardo_product_url(page_num-1), method: "post", class: "btn btn-primary" %>
	</div>
	<div class="col-md-4">
		<div class="text-center">
			Page <%= page_num %>
		</div>
	</div>
	<div class="col-md-4">
		<div class="float-end">
		<%= button_to "Next page", page_leonardo_product_url(page_num+1), method: "post", class: "btn btn-primary" %>
		</div>
	</div>
</div>

dip/app/views/leonardo_products/_navbar.html.erb
<ul class="nav nav-tabs justify-content-center">
	<li class="nav-item">
		<a class="nav-link" href="/parse_tasks">Tasks</a>
	</li>
	<li class="nav-item">
		<a class="nav-link" href="/litres_books">Litres</a>
	</li>
	<li class="nav-item">
		<a class="nav-link active" aria-current="page" href="/leonardo_products">Leonardo</a>
	</li>
</ul>

dip/app/views/leonardo_products/index.html.erb
<%= turbo_stream_from "litres_books" %>
<%= turbo_stream_from "litres_books_page" %>
<%= turbo_stream_from "search_form" %>

<div id="navbar">
	<%= render partial: "layouts/navbar", locals: { active: 3 }%>
</div>

<div id="tabs">
	<%= render partial: "layouts/tabs", locals: { active: 2 }%>
</div>

<div class="container mt-4">
	<% if not notice.nil?%>
		<div class="alert alert-success" role="alert">
			<%= notice %>
		</div>
	<% end %>

	<% if not alert.nil?%>
		<div class="alert alert-danger" role="alert">
			<%= alert %>
		</div>
	<% end %>

	<div class="row">
		<div class="col-4">
			<h1>Leonardo products</h1>

			<div class="vstack gap-3">
				<div id="search_form">
					<%= render partial: "form" %>
				</div>

				<div>
					<%= button_to "Export", "/leonardo_products/export.csv", method: "post", class: "btn btn-primary" %>
				</div>
			</div>
		</div>
		<div class="col-8 border-start">
			<div id="leonardo_products">
				<% if not @leonardo_products.nil? and @page != 0 and not @page.nil?%>
					<%= render partial: "leonardo_products/list", locals: { leonardo_products: @leonardo_products, page_num: @page } %>
				<% end %>
			</div>
		</div>
	</div>
</div>

dip/app/views/leonardo_products/show.html.erb
<div id="navbar">
	<%= render partial: "layouts/navbar", locals: { active: 3 }%>
</div>

<div id="tabs">
	<%= render partial: "layouts/tabs", locals: { active: 2 }%>
</div>

<div class="container mt-4">
	<%= render @leonardo_product %>
	<div>
		<%= link_to "Back to leonardo products", leonardo_products_path %>
	</div>
</div>