dip/config/routes.rb
Rails.application.routes.draw do
	resources :parse_tasks do
		member do
			put 'parse'
			post 'export'
		end
	end

	resources :litres_books, only: [:index, :show] do
		collection do
			post 'search'
			post 'export'
		end
		member do
			post 'page'
		end
	end

	resources :leonardo_products, only: [:index, :show] do
		collection do
			post 'search'
			post 'export'
		end
		member do
			post 'page'
		end
	end

	get 'home', to: "home#index"

	root "home#index"
end

dip/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@litres_genres = LitresBook.distinct.pluck(:main_genre) 
		@leonardo_categories = LeonardoProduct.distinct.pluck(:category_name) 

		@litres_genres_and_count = []
		@litres_genres.each do | genre |
			@litres_genres_and_count.push({ name: genre, count: LitresBook.where(main_genre: genre).length })
		end

		@leonardo_categories_and_count = []
		@leonardo_categories.each do | category |
			@leonardo_categories_and_count.push({ name: category, count: LeonardoProduct.where(category_name: category).length })
		end
	end
end

dip/app/views/home/index.html.erb
<div id="navbar">
	<%= render partial: "layouts/navbar", locals: { active: 1 }%>
</div>

<div class="container mt-4">
	<div class="row">
		<div class="col-6">
			<div class="card" >
				<%= image_tag "litres.jpg", class: "card-img-top "%>
				<div class="card-body">
					<h5 class="card-title">Litres</h5>
					<p class="card-text">Aggregator, distributor and seller of e-books in Russia and CIS countries</p>
				</div>
				<ul class="list-group list-group-flush list-group-numbered">
					<% @litres_genres_and_count.each do |info| %>
						<li class="list-group-item">
						<%= info[:name] %>
						<span class="badge bg-primary rounded-pill"><%= info[:count] %></span>
						</li>
					<% end %>
				</ul>
				<div class="card-body">
					<%= link_to "Go to litres books", litres_books_url, class: "card-link" %> 
				</div>
			</div>
		</div>
		<div class="col-6">
			<div class="card" >
				<%= image_tag "leonardo.jpg", class: "card-img-top "%>
				<div class="card-body">
					<h5 class="card-title">Leonardo</h5>
					<p class="card-text">The largest chain of hobby hypermarkets in Russia in Russia and CIS countries</p>
				</div>
				<ul class="list-group list-group-flush list-group-numbered">
					<% @leonardo_categories_and_count.each do |info| %>
						<li class="list-group-item">
						<%= info[:name] %>
						<span class="badge bg-primary rounded-pill"><%= info[:count] %></span>
						</li>
					<% end %>
				</ul>
				<div class="card-body">
					<%= link_to "Go to leonardo products", leonardo_products_url, class: "card-link" %> 
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-12">
		</div>
	</div>
</div>