dip/config/routes.rb
Rails.application.routes.draw do
	resources :parse_tasks do
		member do
			put 'parse'
			post 'export'
		end
	end

	resources :litres_books, only: [:index, :show] do
		collection do
			post 'search'
			post 'export'
		end
		member do
			post 'page'
		end
	end

	resources :leonardo_products, only: [:index, :show] do
		collection do
			post 'search'
			post 'export'
		end
		member do
			post 'page'
		end
	end

	get 'home', to: "home#index"

	root "home#index"
end

dip/app/models/parse_task.rb
class ParseTask < ApplicationRecord
	validates :name, :status, :web_site, presence: true
	validates :status, inclusion: { in: [1,2,3], 
		message: "%{value} is not a valid size" }
	validates :web_site, inclusion: { in: [1, 2], 
		message: "%{value} is not a valid size" }
	validates :name, length: { in: 1..20, 
		wrong_length: "Length: from 1 to 20" }

	after_update_commit { broadcast_update_to('tasks', partial: 'parse_tasks/tasks', locals: { parse_tasks: ParseTask.all }, target: "tasks") }
end

dip/app/controllers/parse_tasks_controller.rb
class ParseTasksController < ApplicationController
	before_action :set_parse_task, only: %i[ show edit update destroy parse export ]
	before_action :set_task_info, only: %i[ create ]

	def index
		@parse_tasks = ParseTask.all
	end

	def show
	end

	def new
		@parse_task = ParseTask.new
	end

	def edit
		if @parse_task.status != 1
			redirect_to parse_tasks_url, alert: "Parse task is in progress or finished."
		end
	end

	def create
		@parse_task = ParseTask.new(name: @name, web_site: @web_site, status: 1)

		respond_to do |format| if @parse_task.save
				format.html { redirect_to parse_tasks_url, notice: "Parse task #{@parse_task.name} was successfully created." }
			else
				format.html { render :new, status: :unprocessable_entity }
			end
		end
	end

	def update
		@page_urls = []
		@category_names = []
		for line in params[:category]
			@page_urls.push(line.split(",")[0])
			@category_names.push(line.split(",")[1])
		end

		respond_to do |format|
			if @parse_task.update(category_names: @category_names, page_urls: @page_urls)
				format.html { redirect_to parse_tasks_url, notice: "Parse task #{@name} was successfully updated." }
			else
				format.html { render :edit, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		respond_to do |format|
			if @parse_task.status != 2
				format.html { redirect_to parse_tasks_url, notice: "Parse task #{@parse_task.name}was successfully destroyed." }
				@parse_task.destroy
			else
				format.html { redirect_to parse_tasks_url, alert: "Cant delete, because parse task #{@parse_task.name} is in progress." }
			end
		end
	end

	def export
		respond_to do |format|
			logs_text = @parse_task.logs
			format.text { send_data logs_text, filename: "parse_tasks_log.txt", type: 'text; charset=UTF-8;' }
		end
	end

	def parse
		respond_to do |format|
			if check_running_job 
				format.html { redirect_to parse_tasks_url, alert: "Cant parse, because someone parse task is in progress." }
			elsif @parse_task.category_names.nil? or @parse_task.page_urls.nil?
				format.html { redirect_to parse_tasks_url, alert: "Cant parse, because parse task #{@parse_task.name} dont have categories." }
			else
				format.html { redirect_to parse_tasks_url, notice: "Parse task #{@parse_task.name} was successfully added to queue." }
				ParseJob.perform_later(@parse_task)
			end
		end
	end

	private

	def set_parse_task
		@parse_task = ParseTask.find(params[:id])
	end

	def set_task_info
		@name = params[:parse_task][:name]
		@web_site = params[:web_site].to_i
		puts @web_site
	end

	def check_running_job
		return ParseTask.find_by(status: 2) != nil
	end

	def parse_task_params
		params.require(:parse_task).permit(:name, :web_site)
	end
end

dip/app/helpers/parse_tasks_helper.rb
module ParseTasksHelper
end

dip/app/views/parse_tasks/_form_create.html.erb
<%= form_with model: parse_task,  class: "row g-3" do |form| %>

	<% if parse_task.errors.any? %>
		<div style="color: red">
			<h2><%= pluralize(parse_task.errors.count, "error") %> prohibited this parse_task from being saved:</h2>
			<ul>
				<% parse_task.errors.each do |error| %>
					<li><%= error.full_message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="col-md-12">
		<%= form.label :name, class: "form-label", for: "inputName" %>
		<%= form.text_field :name, id: "inputName", class: "form-control" %>
	</div>

	<div class="col-md-12">
		<%= form.label :web_site, class: "form-label", for: "inputWebSite" %>
		<select name="web_site" id="inputWebSite" class="form-select">
			<option value="1">Litres.ru</option>
			<option value="2">Leonardo.by</option>
		</select>
	</div>

	<div class="col-md-12">
		<%= form.submit "Create", class: "btn btn-primary" %>
	</div>
<% end %>

dip/app/views/parse_tasks/_form_edit_leonardo.html.erb
<%= form_with model: parse_task,  class: "row g-3" do |form| %>
	<% if parse_task.errors.any? %>
		<div style="color: red">
			<h2><%= pluralize(parse_task.errors.count, "error") %> prohibited this parse_task from being saved:</h2>
			<ul>
				<% parse_task.errors.each do |error| %>
					<li><%= error.full_message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<% @litres_categories = LitresCategory.all %>
	<% if not @litres_categories.nil? %>
		<% count = 0%>
		<% @litres_categories.each do |litres_category| %>
			<div class="col-md-4">
				<div class="form-check">
					<input class="form-check-input" type="checkbox" value="<%= "#{litres_category.url},#{litres_category.name}" %>" id="check_<%= count %>" name="category[]">
					<label class="form-check-label" for="check_<%= count %>">
						<%= litres_category.name %>
					</label>
				</div>
				<% count += 1 %>
			</div>
		<% end %>
	<% end %>
	<div class="col-md-12">
		<%= form.submit "Create", class: "btn btn-primary" %>
	</div>
<% end %>

dip/app/views/parse_tasks/_form_edit_litres.html.erb
<%= form_with model: parse_task,  class: "row g-3" do |form| %>
	<% if parse_task.errors.any? %>
		<div style="color: red">
			<h2><%= pluralize(parse_task.errors.count, "error") %> prohibited this parse_task from being saved:</h2>
			<ul>
				<% parse_task.errors.each do |error| %>
					<li><%= error.full_message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<% @litres_categories = LitresCategory.all %>
	<% if not @litres_categories.nil? %>
		<% count = 0%>
		<% @litres_categories.each do |litres_category| %>
			<div class="col-md-4">
				<div class="form-check">
					<input class="form-check-input" type="checkbox" value="<%= "#{litres_category.url},#{litres_category.name}" %>" id="check_<%= count %>" name="category[]">
					<label class="form-check-label" for="check_<%= count %>">
						<%= litres_category.name %>
					</label>
				</div>
				<% count += 1 %>
			</div>
		<% end %>
	<% end %>
	<div class="col-md-12">
		<%= form.submit "Create", class: "btn btn-primary" %>
	</div>
<% end %>

dip/app/views/parse_tasks/_log.html.erb
<% logs.each do |log| %>
	<div class="card text-dark bg-info mb-3" style="max-width: 40rem;">
		<div class="card-header"><%= log[:header] %></div>
		<div class="card-body">
			<h5 class="card-title"><%= log[:info] %></h5>
			<p class="card-text"><%= log[:url] %></p>
		</div>
	</div>
<% end %>

dip/app/views/parse_tasks/_navbar.html.erb
<ul class="nav nav-tabs justify-content-center">
	<li class="nav-item">
		<a class="nav-link active" aria-current="page" href="/parse_tasks">Tasks</a>
	</li>
	<li class="nav-item">
		<a class="nav-link" href="/litres_books">Litres</a>
	</li>
	<li class="nav-item">
		<a class="nav-link" href="/leonardo_products">Leonardo</a>
	</li>
</ul>

dip/app/views/parse_tasks/_parse_task.html.erb
<div class="card my-4" style="width: 18rem;">
	<div class="card-body">
		<h5 class="card-title"><%= parse_task.name %>
		<% if parse_task.status == 1 %>
			<span class="badge rounded-pill bg-danger">Free</span>
		<% elsif parse_task.status == 2 %>
			<span class="badge rounded-pill bg-warning text-dark">In progress</span>
		<% else %>
			<span class="badge rounded-pill bg-success">Success</span>
		<% end %>
		</h5>
		<h6 class="card-subtitle mb-2 text-muted">
			<% if parse_task.web_site == 1 %>
				Litres
			<% elsif parse_task.web_site == 2 %>
				Leonardo
			<% else %>
				Something else
			<% end %>
		</h6>
		<div class="card-header">
			Categories
		</div>
		<% if not parse_task.category_names.nil? and not parse_task.page_urls.nil? %>
			<ul class="list-group list-group-flush">
				<% parse_task.category_names.each do |name| %>
					<li class="list-group-item"><%= name %></li>
				<% end %>
			</ul>
		<% end %>
		<p class="card-text"> 
			<strong>Finish date:</strong>
			<%= parse_task.finish_date %>
		</p>
		<% if parse_task.status == 1 %>
			<%= link_to "Edit this parse task", edit_parse_task_path(parse_task), class: "card-link" %> 
			<div class="my-2">
				<% if not parse_task.category_names.nil? and not parse_task.page_urls.nil?  %>
					<%= button_to "Start parsing", parse_parse_task_path(parse_task), method: :put, class: "btn btn-primary" %>
				<% end %>
			</div>
		<% end %>
		<% if parse_task.status == 3 %>
			<div class="my-2">
				<%= button_to "Export logs", "/parse_tasks/#{parse_task.id}/export.txt", method: :post, class: "btn btn-primary" %>
			</div>
		<% end %>
		<% if parse_task.status != 2 %>
			<div class="my-2">
				<%= button_to "Destroy", parse_task, method: :delete, class: "btn btn-primary" %>
			</div>
		<% end %>
	</div>
</div>

dip/app/views/parse_tasks/_tasks.html.erb
<h1>Parse tasks</h1>
<div id="parse_tasks">
  <% parse_tasks.each do |parse_task| %>
	<%= render parse_task %>
  <% end %>
</div>
<%= link_to "New parse task", new_parse_task_path %>

dip/app/views/parse_tasks/edit.html.erb
<div id="navbar">
	<%= render partial: "layouts/navbar", locals: { active: 2 }%>
</div>

<div class="container mt-4 w-50 bg-primary bg-opacity-25 p-4 border border-3 rounded">
	<h2>Editing parse task</h2>
	<%= form_with model: @parse_task, class: "row g-3" do |form| %>
		<% if @parse_task.errors.any? %>
			<div style="color: red">
				<h2><%= pluralize(@parse_task.errors.count, "error") %> prohibited this parse_task from being saved:</h2>
				<ul>
					<% @parse_task.errors.each do |error| %>
						<li><%= error.full_message %></li>
					<% end %>
				</ul>
			</div>
		<% end %>
		<% if @parse_task.web_site == 1 %>
			<% @categories = LitresCategory.all %>
		<% elsif @parse_task.web_site == 2%>
			<% @categories = LeonardoCategory.all %>
		<% end %>
		<% if not @categories.nil? %>
			<% count = 0%>
			<% @categories.each do |category| %>
				<div class="col-md-4">
					<div class="form-check">
						<input class="form-check-input" type="checkbox" value="<%= "#{category.url},#{category.name}" %>" id="check_<%= count %>" name="category[]">
						<label class="form-check-label" for="check_<%= count %>">
							<%= category.name %>
						</label>
					</div>
					<% count += 1 %>
				</div>
			<% end %>
		<% end %>
		<div class="col-md-12">
			<%= form.submit "Create", class: "btn btn-primary" %>
		</div>
	<% end %>
</div>

dip/app/views/parse_tasks/index.html.erb
<%= turbo_stream_from "tasks" %>
<%= turbo_stream_from "log" %>

<div id="navbar">
	<%= render partial: "layouts/navbar", locals: { active: 2 }%>
</div>

<div class="container mt-4">
	<% if not notice.nil?%>
		<div class="alert alert-success" role="alert">
			<%= notice %>
		</div>
	<% end %>

	<% if not alert.nil?%> <div class="alert alert-danger" role="alert">
			<%= alert %>
		</div>
	<% end %>

	<div class="row">
		<div id="tasks" class="col-4 bg-primary bg-opacity-25 border border-3 rounded p-4">
			<%= render partial: "tasks", locals: { parse_tasks: @parse_tasks}%>
		</div>
		<div class="col-8 ps-4">
			<h1> Parsing log </h1>
			<div id="log">
			</div>
		</div>
	</div>
</div>

dip/app/views/parse_tasks/new.html.erb
<div id="navbar">
	<%= render partial: "layouts/navbar", locals: { active: 2 }%>
</div>

<div class="container mt-4 w-25 bg-primary bg-opacity-25 p-4 border border-3 rounded">
	<h2>New parse task</h2>
	<%= render "form_create", parse_task: @parse_task %>
</div>

dip/app/views/parse_tasks/show.html.erb
<div id="navbar">
	<%= render partial: "layouts/navbar", locals: { active: 2 }%>
</div>

<% if not notice.nil?%>
	<div class="alert alert-success" role="alert">
		<%= notice %>
	</div>
<% end %>

<% if not alert.nil?%>
	<div class="alert alert-danger" role="alert">
		<%= alert %>
	</div>
<% end %>

<%= render @parse_task %>

<div>

	<% if @parse_task.status == 1 %>
		<%= link_to "Edit this parse task", edit_parse_task_path(@parse_task) %> |
		<%= button_to "Start parsing", parse_parse_task_url, method: :put %>
	<% end %>

	<%= link_to "Back to parse tasks", parse_tasks_path %>

	<% if @parse_task.status != 2 %>
		<%= button_to "Destroy this parse task", @parse_task, method: :delete %>
	<% end %>
</div>